/*
 Navicat Premium Data Transfer

 Source Server         : booking_core
 Source Server Type    : MySQL
 Source Server Version : 100422
 Source Host           : localhost:3306
 Source Schema         : sports_web

 Target Server Type    : MySQL
 Target Server Version : 100422
 File Encoding         : 65001

 Date: 11/12/2024 21:00:07
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for football_news
-- ----------------------------
DROP TABLE IF EXISTS `football_news`;
CREATE TABLE `football_news`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `title` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `path_image` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `created_at` datetime(0) NULL DEFAULT NULL,
  `type` tinyint(11) NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 28 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of football_news
-- ----------------------------
INSERT INTO `football_news` VALUES (1, 'Trực tiếp bóng đá Lào - Việt Nam: Thầy Kim - Tiến Linh cần 1 trận thắng chạy đà (AFF Cup)', '(Lào - Việt Nam, 20h, 9/12, bảng B, AFF Cup 2024) ĐT Việt Nam hướng đến chiến thắng trong trận ra quân AFF Cup, qua đó hướng đến giải đấu lớn thành công.', 'Đội chủ nhà tiến bộ rõ rệt\r\n\r\nLào đã có sự tiến bộ dưới bàn tay HLV Ha Hyeok Jun, họ cầm hòa Thái Lan 1-1 trong tháng 11 vừa qua. Nhà cầm quân người Hàn Quốc đã chọn trẻ hóa đội tuyển khi gọi gần như toàn cầu thủ U23 cho AFF Cup, trong khi 2 cầu thủ quan trọng trước đây là Soukaphone Vongchiengkham và Billy Ketkeophomphone đều vắng mặt.\r\n\r\n\"Những ngôi sao vàng\" quyết thắng ấn tượng\r\n\r\nĐT Việt Nam sẽ mở màn chiến dịch AFF Cup với trận gặp Lào tại Viêng Chăn. Lào được đánh giá là đối thủ yếu nhất của bảng B nên đây sẽ là cơ hội cho thầy trò HLV Kim Sang Sik bắt đầu giải với một chiến thắng để khích lệ tâm lý cầu thủ.', './resource/image/image1.jpg', '2024-12-02 15:16:02', 1);
INSERT INTO `football_news` VALUES (2, 'HLV Park Hang Seo đến Lào “tiếp lửa” ĐT Việt Nam ra quân AFF Cup', 'Cựu HLV trưởng của ĐT Việt Nam đã di chuyển đến Lào để cổ vũ “Những chiến binh sao vàng” ở trận mở màn bảng B AFF Cup 2024 trước ĐT Lào (20h ngày 9/12).', '\r\n\r\nHLV Park Hang Seo đáp chuyến bay tới Lào để cổ vũ ĐT Việt Nam\r\n\r\n\r\n\r\nDự kiến, “Những chiến binh sao vàng” dù thi đấu trên sân khách nhưng vẫn sẽ nhận được sự cổ vũ của hàng chục ngàn cổ động viên Việt Nam. Giá vé xem trận đấu giữa ĐT Lào và ĐT Việt Nam tối ngày 9/12 chỉ được bán với giá từ 24.000 đồng.\r\n\r\nĐược biết, phần lớn vé trận ra quân của ĐT Việt Nam trên sân vận động quốc gia Lào (sức chứa vào khoảng 25.000 chỗ ngồi) đã được cổ động viên Việt Nam mua. Thầy trò HLV Kim Sang Sik sẽ nhận được sự cổ vũ của đông đảo người hâm mộ bóng đá Việt Nam đang sinh sống và làm việc ở Lào.\r\n\r\nBên cạnh đó, có không ít cổ động viên từ Việt Nam đã kịp có mặt ở thành phố Viêng Chăn để sẵn sàng đồng hành cùng ĐT Việt Nam trong hành trình chinh phục AFF Cup 2024. Trong đó, ĐT Việt Nam dự kiến có một cổ động viên đặc biệt trên khán đài sân vận động quốc gia Lào.\r\n\r\nĐó là ông Park Hang Seo, cựu HLV trưởng của ĐT Việt Nam. Ông Park và vợ đã đáp chuyến bay đến Lào sáng ngày 9/12. Ngay sau khi có mặt ở sân bay, HLV Park Hang Seo nhận được sự quan tâm của một số cổ động viên có mặt ở đây lẫn giới truyền thông.', './resource/image/image2.jpg', '2024-12-03 15:21:45', 1);
INSERT INTO `football_news` VALUES (3, 'ĐT Việt Nam đặc biệt nhất kể từ 2018, thắng Lào để đua vô địch AFF Cup', 'Với \"diện mạo\" đặc biệt ở AFF Cup 2024, liệu ĐT Việt Nam có thể vượt qua mọi chướng ngại để đòi lại ngôi vương Đông Nam Á?', 'Ngoài ra, ĐT Việt Nam không còn trở thành ứng viên số 1 cho ngôi vương sau thất bại trước Thái Lan ở 2 kỳ AFF Cup gần nhất, hay những lần bị Indonesia gieo sầu ở Asian Cup, vòng loại World Cup. Dù vậy, chính việc bước vào giải đấu với vị thế \"cửa dưới\" cũng phần nào giảm bớt sức ép cho thầy trò HLV Kim Sang Sik.\r\n\r\nTrước mắt, nhiệm vụ của ĐT Việt Nam là đánh bại ĐT Lào ở trận ra quân bảng B (20h, 9/12). Đây là mục tiêu nằm trong khả năng bởi \"Những chiến binh sao vàng\" chưa từng thua ĐT Lào. Quá khứ cũng chỉ ra, chiến thắng trước Lào luôn mang tới vận may cho bóng đá Việt Nam ở mỗi kỳ AFF Cup. \r\n\r\nThông tin đáng chú ý về ĐT Việt Nam sẽ có trong Clip 1 phút Bóng đá 24H. Đặc biệt, bản tin hôm nay có sự đồng hành của Công ty IRC Việt Nam. IRC được thành lập tại Nhật Bản từ năm 1926. Đến năm 1997, chính thức đầu tư nhà máy sản xuất săm, lốp xe máy IRC Việt Nam.\r\n\r\nIRC Việt Nam tự hào là nhà sản xuất cung cấp các sản phẩm săm, lốp xe máy và sản phẩm cao su kỹ thuật chính hiệu cho các hãng sản xuất và lắp ráp xe máy nổi tiếng tại Việt Nam như: HONDA, YAMAHA, Vinfast… Các sản phẩm của IRC Việt Nam luôn đáp ứng được những quy trình kiểm định ngặt nghèo nhất về độ bền, độ an toàn và các tính năng kỹ thuật khác.', './resource/image/image3.jpg', '2024-12-06 15:22:50', 1);
INSERT INTO `football_news` VALUES (4, 'Chelsea lỳ lợm, Tottenham & Son Heung Min gục đầu ôm hận', '\"Đòn gió\" của Postecoglou chỉ đem lại hiệu quả trong 15 phút đầu tiên, trong khi Son Heung Min lại bỏ lỡ trong tình huống quyết định.', '\r\n\r\nVan De Ven và Romero bất ngờ xuất hiện ngay từ đầu\r\n\r\n\r\n\r\nBất ngờ đầu tiên đến từ đội hình ra sân. Trước khi trận đấu bắt đầu, không ai ngờ cặp trung vệ Cristian Romero và Micky Van de Ven lại có mặt trong đội hình xuất phát của Tottenham, mặc dù cả hai cầu thủ đều được cho là chấn thương và cần thêm thời gian để hồi phục.\r\n\r\nBình luận viên Paul Merson của Sky Sports đã không khỏi ngạc nhiên: \"Thật không thể tin nổi!\". Sự xuất hiện của Romero và Van de Ven đã giúp Tottenham có được sự cân bằng với Chelsea.\r\n\r\nBất ngờ thứ hai đến từ hai pha trượt chân của Cucurella. Đây là những lỗi hiếm gặp đặc biệt ở các cầu thủ Ngoại hạng Anh, bởi họ thường có khả năng giữ thăng bằng rất tốt. Tuy nhiên, hậu vệ người Tây Ban Nha lại mắc phải hai lỗi trong chỉ vài phút. \r\n\r\nBất ngờ thứ ba, quyết định của HLV Enzo Maresca khi vẫn giữ Cucurella trên sân, dù cầu thủ này vừa phạm hai sai lầm. Nhiều HLV có thể sẽ thay người ngay lập tức để trừng phạt và bảo vệ tâm lý cầu thủ, nhưng Maresca lại tin tưởng vào khả năng phục hồi của Cucurella. Chính quyết định này đã giúp Cucurella thi đấu tốt hơn và có một pha kiến tạo.', './resource/image/image4.jpg', '2024-12-05 15:24:53', 1);
INSERT INTO `football_news` VALUES (5, '\"Soi kèo\" lượt 6 vòng bảng Cúp C1: Căng thẳng Man City đấu Juventus, Real - Barca âu lo', 'Lượt đấu thứ 6 của vòng bảng Champions League hứa hẹn mang đến cho người hâm mộ những trận cầu đỉnh cao, với nhiều cuộc thư hùng giữa các ông lớn của bóng đá châu Âu.', 'Cuối tuần qua, Man City lại sa lầy trên sân Crystal Palace trong trận cầu nhà đương kim vô địch Ngoại hạng Anh 2 lần phải bám đuổi. Thậm chí, họ còn phải chơi thiếu người trong khoảng thời gian cuối trận và việc có điểm ra về là may mắn lớn với nửa xanh thành Manchester.\r\n\r\nTrong tình cảnh này, việc phải làm khách đến sân của Juventus rõ ràng là điều Man City không hề mong muốn. May cho đội bóng Anh là \"Bà đầm già thành Turin\" cũng không có phong độ tốt. Juventus đang trải qua chuỗi 4 trận liên tiếp có kết quả hòa.\r\n\r\nCác chuyên gia đánh giá, trận đấu giữa Juventus và Man City là trận hòa tiếp theo của hai đội. Bởi lẽ vào thời điểm này, không đội bóng nào vượt trội để áp đảo được đối phương. Tỷ số của cuộc thư hùng này có thể 1-1.\r\n\r\nReal Madrid - Barca đối diện những trận đấu khó\r\n\r\nCả 2 gã khổng lồ của bóng đá Tây Ban Nha đều phải làm khách ở lượt đấu thứ 6 vòng bảng Champions League. Trong đó, Barcelona hành quân đến sân của Dortmund, trong khi Real Madrid đụng độ đội đầu bảng Serie A, Atalanta.', './resource/image/image5.jpg', '2024-12-07 15:26:23', 1);
INSERT INTO `football_news` VALUES (6, 'Trực tiếp bóng đá Lào - Việt Nam: Thầy Kim - Tiến Linh cần 1 trận thắng chạy đà (AFF Cup)', '(Lào - Việt Nam, 20h, 9/12, bảng B, AFF Cup 2024) ĐT Việt Nam hướng đến chiến thắng trong trận ra quân AFF Cup, qua đó hướng đến giải đấu lớn thành công.', 'Đội chủ nhà tiến bộ rõ rệt\r\n\r\nLào đã có sự tiến bộ dưới bàn tay HLV Ha Hyeok Jun, họ cầm hòa Thái Lan 1-1 trong tháng 11 vừa qua. Nhà cầm quân người Hàn Quốc đã chọn trẻ hóa đội tuyển khi gọi gần như toàn cầu thủ U23 cho AFF Cup, trong khi 2 cầu thủ quan trọng trước đây là Soukaphone Vongchiengkham và Billy Ketkeophomphone đều vắng mặt.\r\n\r\n\"Những ngôi sao vàng\" quyết thắng ấn tượng\r\n\r\nĐT Việt Nam sẽ mở màn chiến dịch AFF Cup với trận gặp Lào tại Viêng Chăn. Lào được đánh giá là đối thủ yếu nhất của bảng B nên đây sẽ là cơ hội cho thầy trò HLV Kim Sang Sik bắt đầu giải với một chiến thắng để khích lệ tâm lý cầu thủ.', './resource/image/image6.jpg', '2024-12-02 15:16:02', 0);
INSERT INTO `football_news` VALUES (7, 'Trực tiếp bóng đá Juventus - Man City: \"Vua hòa\" gặp kẻ đang khốn khó (Champions League)', 'Juventus - Man City, 3h, 12/12, vòng bảng Champions League) Man City đang rất chật vật, còn Juventus thua ít nhưng hóa rất nhiều.', 'Tẻ nhạt nhưng chắc chắn\r\n\r\nChỉ mới có 8 điểm sau 5 trận tại Champions League, nhưng Juventus chỉ mới nhận 1 thất bại duy nhất ở mọi đấu trường trong mùa giải năm nay. Điểm yếu duy nhất của \"Bianconeri\" là việc họ để hòa quá nhiều, với 9 trận ở Serie A và 2 trận tại cúp C1.\r\n\r\nVới 1 hàng phòng ngự kín kẽ và có thực lực, Juventus sẽ không ngại khi phải đối đầu với những ngôi sao tấn công ở bên phía Man City. Họ từ đầu mùa giải chỉ thua 1 trận trên sân nhà ở mọi mặt trận.\r\n\r\nLoay hoay thoát khỏi khủng hoảng\r\n\r\nMan City vẫn chưa thoát khỏi khủng hoảng khi trong trận đấu gần nhất, họ bị Crystal Palace cầm chân với tỷ số 2-2. Trong 3 trận đấu sắp tới, Man City sẽ lần lượt chạm trán với Juventus, Man United và Aston Villa, những trận đấu cực kỳ khó khăn với thầy trò HLV Pep Guardiola.\r\n\r\nChỉ tính riêng tại đấu trường Champions League, thất bại 1-4 trước Sporting CP và trận hòa 3-3 trước Feyenoord dù đã dẫn trước 3-0, khiến Man City bị tụt lại trên bảng xếp hạng với chỉ 8 điểm sau 5 trận. Do đó, The Citizens sẽ phải rất nỗ lực nếu vẫn muốn cạnh tranh 1 vị trí trong top 8.', './resource/image/image7.jpg', '2024-12-02 15:16:02', 0);
INSERT INTO `football_news` VALUES (9, 'Trực tiếp bóng đá Arsenal - Monaco: Điểm tựa Emirates (Cúp C1)', '(3h, 12/12, lượt 6 vòng bảng Champions League) Arsenal cần thắng Monaco để trở lại vị trí trong top 8 trên bảng xếp hạng.', 'Điểm tựa Emirates\r\n\r\n“Pháo đài” Emirates chính là điểm tựa của Arsenal mùa này. Đoàn quân của HLV Mikel Arteta toàn thắng trước Shakhtar Donetsk và PSG trong 2 cả trận được chơi trên sân nhà ở Champions League năm nay. Hơn nữa, “Pháo thủ” đã có 4 trận giữ sạch lưới trong 6 trận sân nhà gần nhất. Đội bóng thành London cũng đang bất bại tại “tổ ấm” của mình trên mọi đấu trường mùa này, thắng 7 trong 8 trận đã đấu.\r\n\r\nMonaco không ngán Arsenal\r\n\r\nVề đối đầu, Monaco không hề lép vế trước Arsenal. Đội bóng Công quốc đã lấy điểm của Arsenal ở 3 trong 4 lần chạm trán gần nhất, 2 trong số đó đến ở giải giao hữu Emirates Cup. Lần gần nhất hai đội gặp gỡ ở Cúp C1 là vòng 1/8 mùa giải 2014/15. Khi đó, Monaco đã đánh bại Arsenal với tỉ số 3-1 ngay tại Emirates và tiễn thầy trò HLV Arsene Wenger khỏi Champions League nhờ luật bàn thắng sân khách.', './resource/image/image9.jpg', '2024-12-02 15:16:02', 0);
INSERT INTO `football_news` VALUES (10, 'Số phận 2 cầu thủ Liverpool được “định đoạt” sau trận thắng Girona', 'Liverpool tiếp tục duy trì ngôi đầu bảng Champions League sau chiến thắng tối thiểu 1-0 trước Girona. Bàn thắng duy nhất của trận đấu được ghi từ chấm phạt đền bởi Mohamed Salah, trong khi thủ môn Alisson Becker xuất sắc cản phá 5 tình huống nguy hiểm để giữ sạch lưới.', '\r\n\r\nAlisson trở lại và lập tức thể hiện đẳng cấp cho Liverpool\r\n\r\n\r\n\r\nMặc dù vừa trở lại sau chấn thương, Alisson một lần nữa chứng minh lý do vì sao anh vẫn là lựa chọn không thể thay thế của Liverpool trong suốt 6 năm qua. Kể từ khi gia nhập từ AS Roma, thủ thành người Brazil đã thể hiện sự ổn định tuyệt vời, không chỉ trong khâu cản phá mà còn ở khả năng chơi chân - điều vượt trội so với bất kỳ người gác đền nào mà Liverpool từng sở hữu.\r\n\r\nSự tiến bộ của Caoimhin Kelleher gần đây làm dấy lên câu hỏi liệu đã đến lúc Liverpool cần đặt niềm tin vào thủ môn trẻ tuổi hơn và xem xét tương lai của Alisson. Tuy nhiên, màn trình diễn ổn định của Alisson khiến ban lãnh đạo khó lòng đáp ứng mong muốn được bắt chính thường xuyên của Kelleher ở mùa giải tới.\r\n\r\nKelleher được xem là \"thủ môn dự bị xuất sắc nhất thế giới\" và đã góp phần không nhỏ trong các danh hiệu cúp mà Liverpool giành được hơn 2 năm qua. Dù vậy, với phong độ cao của Alisson khi mới chỉ 32 tuổi, cùng sự hiện diện của những thủ môn như Vítězslav Jaroš và thỏa thuận chiêu mộ Giorgi Mamardashvili, cơ hội cho Kelleher tại Liverpool ngày càng mong manh.', './resource/image/image10.jpg', '2024-12-02 15:16:02', 0);
INSERT INTO `football_news` VALUES (11, 'Barca bị Real “phả lửa vào gáy”, Hansi Flick đừng để sai một ly đi một dặm', 'Barcelona đang trải qua giai đoạn thi đấu đáng thất vọng tại La Liga. Trận hòa 2-2 trước Real Betis tuần trước không chỉ làm chậm bước tiến của đội bóng xứ Catalunya mà còn là minh chứng rõ ràng cho sự bất ổn về thành tích. Trong 5 trận gần nhất tại La Liga, Barcelona chỉ giành được 5/15 điểm tối đa, với vỏn vẹn 1 chiến thắng, 2 trận hòa và 2 thất bại.', 'Đây là một sự sụt giảm nghiêm trọng nếu so sánh với chuỗi phong độ thăng hoa đầu mùa. Trong 12 vòng đầu tiên, Barcelona thắng tới 11 trận, đạt tỷ lệ giành điểm lên tới 91,6% (33/36 điểm). Tuy nhiên, lịch thi đấu dày đặc cùng sự thiếu ổn định trong đội hình đã khiến đội bóng đánh mất sự sắc bén 2 tuần gần đây.\r\n\r\nTrận hòa tại SVĐ Benito Villamarín trước Real Betis là ví dụ điển hình. Dù có nhiều cơ hội ghi bàn rõ ràng, Barcelona vẫn không thể “kết liễu” đối thủ, dẫn đến màn trình diễn nhạt nhòa và thiếu đột biến. Những pha phạm lỗi không đáng có, điển hình là tình huống của Frenkie de Jong dẫn đến quả phạt đền, giúp đối thủ cầm hòa đáng tiếc.', './resource/image/image11.jpg', '2024-12-02 15:16:02', 0);
INSERT INTO `football_news` VALUES (12, 'HLV Ancelotti kém vui dù Real Madrid thắng, Gyokeres \"gây sốt châu Âu\" bị giải mã (Clip 1 phút)', 'HLV Carlo Ancelotti có lí do để lo lắng sau chiến thắng nhọc nhằn của Real Madrid bởi đội chủ sân Bernabeu quá phụ thuộc vào phong độ của các ngôi sao như Mbappe.', 'Real Madrid vừa giành chiến thắng kịch tính 3-2 trước Atalanta ở lượt trận thứ 6 vòng bảng Champions League. Dù vậy, HLV Carlo Ancelotti không để lại dấu ấn quá đậm nét, thậm chí chuỗi thành tích thất thường của Real thời gian gần đây phụ thuộc rất nhiều vào phong độ của Mbappe và dàn sao.\r\n\r\nCũng ở Champions League, Sporting Lisbon nhận thất bại trước Club Brugge và nối dài chuỗi trận thua liên tiếp lên con số 4. Chuỗi trận tệ hại của đội bóng Bồ Đào Nha trùng thời điểm Viktor Gyokeres, chân sút đang \"gây sốt\" châu Âu chỉ đóng góp 1 pha lập công. \r\n\r\nTrường hợp của Gyokeres có nét tương đồng Artem Dovbyk hay Alexander Sorloth, 2 tiền đạo cạnh tranh Vua phá lưới La Liga mùa trước nhưng chật vật trong màu áo AS Roma và Atletico Madrid mùa này.\r\n\r\nThông tin đáng chú ý về Champions League và các ngôi sao, HLV danh tiếng sẽ có trong bản tin Clip 1 phút Bóng đá 24H ngày 11/12, mời các bạn đón xem!', './resource/image/image12.jpg', '2024-12-02 15:16:02', 0);
INSERT INTO `football_news` VALUES (13, 'Liverpool mỗi trận thắng là một kỷ lục, ôm mộng lớn ở cúp C1', 'Liverpool tiếp tục hành trình hoàn hảo tại Champions League mùa này với 2 kỷ lục được thiết lập trong chiến thắng 1-0 trước Girona, nắm chắc tấm vé vào vòng 16 đội.', 'Quan trọng hơn, đội bóng vùng Merseyside giữ sạch lưới trong 5 trận liên tiếp, thành tích chỉ từng đạt được vào các mùa giải 2005 (mùa họ lên ngôi vô địch) và 1984. Hàng thủ vững chắc của Liverpool, dưới sự chỉ huy của Virgil van Dijk và thủ môn Alisson, đang là điểm tựa vững vàng cho hành trình chinh phục danh hiệu Champions League.\r\n\r\nTrước một đối thủ khó chịu như Girona, Liverpool đã phải nhận tới 13 cú sút nhưng không một lần vào lưới nhặt bóng. Sự kiên cố trong khung thành đã giúp đoàn quân của Arne Slot trở nên khó bị đánh bại hơn bao giờ hết. Đây là mùa giải “Lữ đoàn Đỏ” thể hiện phong độ ổn định đáng gờm từ Ngoại hạng Anh tới Champions League.\r\n\r\n', './resource/image/image13.jpg', '2024-12-02 15:16:02', 0);
INSERT INTO `football_news` VALUES (14, 'Đội bóng Ai Cập muốn chiêu mộ Ronaldo, chờ đấu Messi ở FIFA Club World Cup', 'Al Ahly đang có kế hoạch chiêu mộ Ronaldo trong bối cảnh họ nằm chung bảng với Inter Miami ở FIFA Club World Cup 2025.', '\r\n\r\nRonaldo liệu có đến Ai Cập chơi bóng?\r\n\r\n\r\n\r\nNếu thương vụ kể trên thành công, Al Ahly sẽ nâng cao đáng kể thương hiệu CLB. Chưa kể họ còn có thể tạo ra được sức hút lớn ở trận gặp Inter Miami tại FIFA Club World Cup 2025. Ronaldo và Messi đã ở bên kia sườn dốc sự nghiệp nhưng các CĐV luôn trông đợi 2 siêu sao này có dịp chạm mặt nhau. \r\n\r\nTuy nhiên để đưa Ronaldo rời khỏi Al Nassr vào thời điểm hiện tại là bài toán hóc búa đối với Al Ahly, kể cả dưới dạng cho mượn. CR7 còn hợp đồng đến hè năm 2025 với Al Nassr và hiện siêu sao người Bồ Đào Nha nhận mức thu nhập lên đến 200 triệu euro/năm. \r\n\r\nAl Ahly là đội bóng hàng đầu của Ai Cập. Nhưng ngân sách của họ không thực sự dồi dào để tạo nên \"bom tấn\" trên thị trường chuyển nhượng. \r\n\r\nTrở lại với FIFA Club World Cup 2025, giải dự kiến diễn ra từ ngày 15/6 cho đến ngày 13/7 năm sau, được tổ chức trên 12 sân vận động tại 11 thành phố của Mỹ. Đây là năm đầu tiên sân chơi này mở rộng quy mô thi đấu như vậy. \r\n\r\nDự kiến mức thưởng ở FIFA Club World Cup 2025 rất cao. Mỗi CLB khi tham dự có thể nhận khoảng 50 triệu USD, chưa bao gồm các khoản tiền thưởng dựa trên thành tích thi đấu. Đội vô địch sẽ nhận số tiền lên tới 100 triệu USD.', './resource/image/image14.jpg', '2024-12-07 17:23:47', 0);
INSERT INTO `football_news` VALUES (15, 'Ngỡ ngàng kẻ ngổ ngáo bóng đá Đức bị loại ở Cúp C1 sau 6 trận thua', 'Liverpool toàn thắng 6 trận nhưng chưa thể là đội đâu tiên ghi danh vòng 1/8 Champions League. Trong khi đó, Leipzig trở thành đội bóng đầu tiên bị loại sau vòng bảng mùa giải 2024/25.', 'Trong trận đấu buộc phải thắng, Leipzig lại để thủng lưới ngay phút thứ 3 sau khi McGinn mở tỷ số cho Aston Villa. Trận này, Leipzig thi đấu với tinh thần đáng khen. Đến phút 62, đội bóng Đức gỡ hòa 2-2 và tràn đầy quyết tâm hướng đến chiến thắng đầu tiên.\r\n\r\nTuy nhiên, sự ngây thơ về mặt chiến thuật cũng như thiếu bản lĩnh trong thời khắc quyết định khiến Leipzig phải trả giá. Phút 85, Barkley ấn định chiến thắng 3-2 cho Aston Villa. Đội bóng Anh ra về với 3 điểm trọn vẹn, tạm leo lên vị trí thứ 3 và sáng cửa đoạt vé thẳng vào vòng 1/8 Champions League.\r\n\r\nTrong khi đó, Leipzig đau đớn bị loại ngay sau vòng bảng. Sau 6 trận, đại diện của Bundesliga toàn thua, ghi được 6 bàn nhưng thủng lưới 13 lần.\r\n\r\nLúc này PSG đang là đội xếp thứ 24, tức là vị trí cuối cùng đủ điều kiện để lọt vào vòng play-off. Nhà vô địch bóng đá Pháp có 7 điểm. Điều đó có nghĩa dù có thắng cả 2 lượt cuối với Sporting Lisbon và Sturm Graz, Leipzig vẫn không đủ điều kiện vượt qua vòng bảng. Họ trở thành đội bóng đầu tiên bị loại khỏi Champions League sau vòng bảng.\r\n\r\n6 đội bóng đã đánh bại Leipzig ở Champions League mùa này lần lượt là Atletico Madrid, Juventus, Liverpool, Celtic, Inter Milan và Aston Villa. Trong 6 trận thua kể trên, chỉ có Celtic thắng cách biệt 2 bàn, các đội còn lại đều thắng với cách biệt tối thiểu.', './resource/image/image15.jpg', '2024-12-06 17:23:53', 0);
INSERT INTO `football_news` VALUES (16, 'LỊCH THI ĐẤU BÓNG ĐÁ HÔM NAY MỚI NHẤT: Nóng Ngoại hạng Anh, Việt Nam đấu Lào ở AFF Cup', 'Những giải đấu, trận đấu bóng đá hấp dẫn sẽ có trong lịch thi đấu bóng đá hôm nay và ngày mai được cập nhật mới nhất, chính xác nhất.', 'Đội chủ nhà tiến bộ rõ rệt\r\n\r\nLào đã có sự tiến bộ dưới bàn tay HLV Ha Hyeok Jun, họ cầm hòa Thái Lan 1-1 trong tháng 11 vừa qua. Nhà cầm quân người Hàn Quốc đã chọn trẻ hóa đội tuyển khi gọi gần như toàn cầu thủ U23 cho AFF Cup, trong khi 2 cầu thủ quan trọng trước đây là Soukaphone Vongchiengkham và Billy Ketkeophomphone đều vắng mặt.\r\n\r\n\"Những ngôi sao vàng\" quyết thắng ấn tượng\r\n\r\nĐT Việt Nam sẽ mở màn chiến dịch AFF Cup với trận gặp Lào tại Viêng Chăn. Lào được đánh giá là đối thủ yếu nhất của bảng B nên đây sẽ là cơ hội cho thầy trò HLV Kim Sang Sik bắt đầu giải với một chiến thắng để khích lệ tâm lý cầu thủ.', './resource/image/image16.jpg', '2024-12-02 15:16:02', 0);
INSERT INTO `football_news` VALUES (17, 'Lịch thi đấu cúp C1 - Champions League 2024/2025 mới nhất', 'Những trận đấu \"nảy lửa\" sẽ có trong lịch đấu bóng đá Cúp C1 - CHAMPIONS LEAGUE 2024/25.', 'Đội chủ nhà tiến bộ rõ rệt\r\n\r\nLào đã có sự tiến bộ dưới bàn tay HLV Ha Hyeok Jun, họ cầm hòa Thái Lan 1-1 trong tháng 11 vừa qua. Nhà cầm quân người Hàn Quốc đã chọn trẻ hóa đội tuyển khi gọi gần như toàn cầu thủ U23 cho AFF Cup, trong khi 2 cầu thủ quan trọng trước đây là Soukaphone Vongchiengkham và Billy Ketkeophomphone đều vắng mặt.\r\n\r\n\"Những ngôi sao vàng\" quyết thắng ấn tượng\r\n\r\nĐT Việt Nam sẽ mở màn chiến dịch AFF Cup với trận gặp Lào tại Viêng Chăn. Lào được đánh giá là đối thủ yếu nhất của bảng B nên đây sẽ là cơ hội cho thầy trò HLV Kim Sang Sik bắt đầu giải với một chiến thắng để khích lệ tâm lý cầu thủ.', './resource/image/image17.jpg', '2024-12-06 17:23:53', 1);
INSERT INTO `football_news` VALUES (18, 'Lịch trực tiếp bóng đá và link xem trực tiếp hôm nay: Việt Nam đấu Lào kênh nào?', 'Trân trọng gửi tới quý độc giả lịch trực tiếp bóng đá hôm nay, lịch truyền hình trực tiếp những trận đấu, và link trực tiếp diễn biến trận đấu diễn ra trong ngày.', 'Đội chủ nhà tiến bộ rõ rệt\r\n\r\nLào đã có sự tiến bộ dưới bàn tay HLV Ha Hyeok Jun, họ cầm hòa Thái Lan 1-1 trong tháng 11 vừa qua. Nhà cầm quân người Hàn Quốc đã chọn trẻ hóa đội tuyển khi gọi gần như toàn cầu thủ U23 cho AFF Cup, trong khi 2 cầu thủ quan trọng trước đây là Soukaphone Vongchiengkham và Billy Ketkeophomphone đều vắng mặt.\r\n\r\n\"Những ngôi sao vàng\" quyết thắng ấn tượng\r\n\r\nĐT Việt Nam sẽ mở màn chiến dịch AFF Cup với trận gặp Lào tại Viêng Chăn. Lào được đánh giá là đối thủ yếu nhất của bảng B nên đây sẽ là cơ hội cho thầy trò HLV Kim Sang Sik bắt đầu giải với một chiến thắng để khích lệ tâm lý cầu thủ.', './resource/image/image18.jpg', '2024-12-02 15:16:02', 1);
INSERT INTO `football_news` VALUES (19, 'Lịch thi đấu bóng đá Ngoại hạng Anh 2024/2025 mới nhất', 'Cập nhật lịch thi đấu bóng đá Ngoại Hạng Anh 2024/2025 bắt đầu diễn ra từ 8/2024 tới 5/2025.', 'Đội chủ nhà tiến bộ rõ rệt\r\n\r\nLào đã có sự tiến bộ dưới bàn tay HLV Ha Hyeok Jun, họ cầm hòa Thái Lan 1-1 trong tháng 11 vừa qua. Nhà cầm quân người Hàn Quốc đã chọn trẻ hóa đội tuyển khi gọi gần như toàn cầu thủ U23 cho AFF Cup, trong khi 2 cầu thủ quan trọng trước đây là Soukaphone Vongchiengkham và Billy Ketkeophomphone đều vắng mặt.\r\n\r\n\"Những ngôi sao vàng\" quyết thắng ấn tượng\r\n\r\nĐT Việt Nam sẽ mở màn chiến dịch AFF Cup với trận gặp Lào tại Viêng Chăn. Lào được đánh giá là đối thủ yếu nhất của bảng B nên đây sẽ là cơ hội cho thầy trò HLV Kim Sang Sik bắt đầu giải với một chiến thắng để khích lệ tâm lý cầu thủ.', './resource/image/image19.jpg', '2024-12-02 15:16:02', 1);
INSERT INTO `football_news` VALUES (21, 'Lịch thi đấu AFF Cup 2024 mới nhất, lịch thi đấu đội tuyển Việt Nam', '(Lào - Việt Nam, 20h, 9/12, bảng B, AFF Cup 2024) ĐT Việt Nam hướng đến chiến thắng trong trận ra quân AFF Cup, qua đó hướng đến giải đấu lớn thành công.', 'Đội chủ nhà tiến bộ rõ rệt\r\n\r\nLào đã có sự tiến bộ dưới bàn tay HLV Ha Hyeok Jun, họ cầm hòa Thái Lan 1-1 trong tháng 11 vừa qua. Nhà cầm quân người Hàn Quốc đã chọn trẻ hóa đội tuyển khi gọi gần như toàn cầu thủ U23 cho AFF Cup, trong khi 2 cầu thủ quan trọng trước đây là Soukaphone Vongchiengkham và Billy Ketkeophomphone đều vắng mặt.\r\n\r\n\"Những ngôi sao vàng\" quyết thắng ấn tượng\r\n\r\nĐT Việt Nam sẽ mở màn chiến dịch AFF Cup với trận gặp Lào tại Viêng Chăn. Lào được đánh giá là đối thủ yếu nhất của bảng B nên đây sẽ là cơ hội cho thầy trò HLV Kim Sang Sik bắt đầu giải với một chiến thắng để khích lệ tâm lý cầu thủ.', './resource/image/image21.jpg', '2024-12-06 17:23:53', 0);
INSERT INTO `football_news` VALUES (22, 'Lịch thi đấu bóng đá Tây Ban Nha 2024/2025 mới nhất', '(Lào - Việt Nam, 20h, 9/12, bảng B, AFF Cup 2024) ĐT Việt Nam hướng đến chiến thắng trong trận ra quân AFF Cup, qua đó hướng đến giải đấu lớn thành công.', 'Đội chủ nhà tiến bộ rõ rệt\r\n\r\nLào đã có sự tiến bộ dưới bàn tay HLV Ha Hyeok Jun, họ cầm hòa Thái Lan 1-1 trong tháng 11 vừa qua. Nhà cầm quân người Hàn Quốc đã chọn trẻ hóa đội tuyển khi gọi gần như toàn cầu thủ U23 cho AFF Cup, trong khi 2 cầu thủ quan trọng trước đây là Soukaphone Vongchiengkham và Billy Ketkeophomphone đều vắng mặt.\r\n\r\n\"Những ngôi sao vàng\" quyết thắng ấn tượng\r\n\r\nĐT Việt Nam sẽ mở màn chiến dịch AFF Cup với trận gặp Lào tại Viêng Chăn. Lào được đánh giá là đối thủ yếu nhất của bảng B nên đây sẽ là cơ hội cho thầy trò HLV Kim Sang Sik bắt đầu giải với một chiến thắng để khích lệ tâm lý cầu thủ.', './resource/image/image22.jpg', '2024-12-02 15:16:02', 0);
INSERT INTO `football_news` VALUES (23, 'Lịch thi đấu bóng đá Conference League 2024/2025 mới nhất', '(Lào - Việt Nam, 20h, 9/12, bảng B, AFF Cup 2024) ĐT Việt Nam hướng đến chiến thắng trong trận ra quân AFF Cup, qua đó hướng đến giải đấu lớn thành công.', 'Đội chủ nhà tiến bộ rõ rệt\r\n\r\nLào đã có sự tiến bộ dưới bàn tay HLV Ha Hyeok Jun, họ cầm hòa Thái Lan 1-1 trong tháng 11 vừa qua. Nhà cầm quân người Hàn Quốc đã chọn trẻ hóa đội tuyển khi gọi gần như toàn cầu thủ U23 cho AFF Cup, trong khi 2 cầu thủ quan trọng trước đây là Soukaphone Vongchiengkham và Billy Ketkeophomphone đều vắng mặt.\r\n\r\n\"Những ngôi sao vàng\" quyết thắng ấn tượng\r\n\r\nĐT Việt Nam sẽ mở màn chiến dịch AFF Cup với trận gặp Lào tại Viêng Chăn. Lào được đánh giá là đối thủ yếu nhất của bảng B nên đây sẽ là cơ hội cho thầy trò HLV Kim Sang Sik bắt đầu giải với một chiến thắng để khích lệ tâm lý cầu thủ.', './resource/image/image23.jpg', '2024-12-06 17:23:53', 0);
INSERT INTO `football_news` VALUES (24, 'Lịch thi đấu BÓNG ĐÁ PHÁP 2024/2025 mới nhất\r\nLịch thi đấu BÓNG ĐÁ PHÁP 2024/2025 mới nhất', '(Lào - Việt Nam, 20h, 9/12, bảng B, AFF Cup 2024) ĐT Việt Nam hướng đến chiến thắng trong trận ra quân AFF Cup, qua đó hướng đến giải đấu lớn thành công.', 'Đội chủ nhà tiến bộ rõ rệt\r\n\r\nLào đã có sự tiến bộ dưới bàn tay HLV Ha Hyeok Jun, họ cầm hòa Thái Lan 1-1 trong tháng 11 vừa qua. Nhà cầm quân người Hàn Quốc đã chọn trẻ hóa đội tuyển khi gọi gần như toàn cầu thủ U23 cho AFF Cup, trong khi 2 cầu thủ quan trọng trước đây là Soukaphone Vongchiengkham và Billy Ketkeophomphone đều vắng mặt.\r\n\r\n\"Những ngôi sao vàng\" quyết thắng ấn tượng\r\n\r\nĐT Việt Nam sẽ mở màn chiến dịch AFF Cup với trận gặp Lào tại Viêng Chăn. Lào được đánh giá là đối thủ yếu nhất của bảng B nên đây sẽ là cơ hội cho thầy trò HLV Kim Sang Sik bắt đầu giải với một chiến thắng để khích lệ tâm lý cầu thủ.', './resource/image/image24.jpg', '2024-12-02 15:16:02', 0);
INSERT INTO `football_news` VALUES (25, 'Lịch thi đấu BÓNG ĐÁ ĐỨC - Bundesliga 2024/2025 mới nhất', '(Lào - Việt Nam, 20h, 9/12, bảng B, AFF Cup 2024) ĐT Việt Nam hướng đến chiến thắng trong trận ra quân AFF Cup, qua đó hướng đến giải đấu lớn thành công.', 'Đội chủ nhà tiến bộ rõ rệt\r\n\r\nLào đã có sự tiến bộ dưới bàn tay HLV Ha Hyeok Jun, họ cầm hòa Thái Lan 1-1 trong tháng 11 vừa qua. Nhà cầm quân người Hàn Quốc đã chọn trẻ hóa đội tuyển khi gọi gần như toàn cầu thủ U23 cho AFF Cup, trong khi 2 cầu thủ quan trọng trước đây là Soukaphone Vongchiengkham và Billy Ketkeophomphone đều vắng mặt.\r\n\r\n\"Những ngôi sao vàng\" quyết thắng ấn tượng\r\n\r\nĐT Việt Nam sẽ mở màn chiến dịch AFF Cup với trận gặp Lào tại Viêng Chăn. Lào được đánh giá là đối thủ yếu nhất của bảng B nên đây sẽ là cơ hội cho thầy trò HLV Kim Sang Sik bắt đầu giải với một chiến thắng để khích lệ tâm lý cầu thủ.', './resource/image/image25.jpg', '2024-12-06 17:23:53', 0);
INSERT INTO `football_news` VALUES (26, 'Lịch thi đấu bóng đá Ý 2024/2025 mới nhất\r\nLịch thi đấu bóng đá Ý 2024/2025 mới nhất', '(Lào - Việt Nam, 20h, 9/12, bảng B, AFF Cup 2024) ĐT Việt Nam hướng đến chiến thắng trong trận ra quân AFF Cup, qua đó hướng đến giải đấu lớn thành công.', 'Đội chủ nhà tiến bộ rõ rệt\r\n\r\nLào đã có sự tiến bộ dưới bàn tay HLV Ha Hyeok Jun, họ cầm hòa Thái Lan 1-1 trong tháng 11 vừa qua. Nhà cầm quân người Hàn Quốc đã chọn trẻ hóa đội tuyển khi gọi gần như toàn cầu thủ U23 cho AFF Cup, trong khi 2 cầu thủ quan trọng trước đây là Soukaphone Vongchiengkham và Billy Ketkeophomphone đều vắng mặt.\r\n\r\n\"Những ngôi sao vàng\" quyết thắng ấn tượng\r\n\r\nĐT Việt Nam sẽ mở màn chiến dịch AFF Cup với trận gặp Lào tại Viêng Chăn. Lào được đánh giá là đối thủ yếu nhất của bảng B nên đây sẽ là cơ hội cho thầy trò HLV Kim Sang Sik bắt đầu giải với một chiến thắng để khích lệ tâm lý cầu thủ.', './resource/image/image26.jpg', '2024-12-02 15:16:02', 0);

-- ----------------------------
-- Table structure for match_results
-- ----------------------------
DROP TABLE IF EXISTS `match_results`;
CREATE TABLE `match_results`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `team1` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `team2` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `score1` int(11) NOT NULL,
  `score2` int(11) NOT NULL,
  `time_begin` datetime(0) NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 6 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of match_results
-- ----------------------------
INSERT INTO `match_results` VALUES (1, 'West Ham United', 'Wolverhampton Wanderers', 2, 1, '2024-12-10 13:37:38');
INSERT INTO `match_results` VALUES (2, 'Tottenham Hotspur', 'Chelsea', 3, 4, '2024-12-08 13:38:35');
INSERT INTO `match_results` VALUES (3, 'Arsenal', 'Fulham', 1, 1, '2024-12-08 13:39:37');
INSERT INTO `match_results` VALUES (4, 'Manchester United\r\n', 'Nottingham Forest', 2, 3, '2024-12-06 13:41:39');
INSERT INTO `match_results` VALUES (5, '\r\nManchester City', 'Crystal Palace\r\n', 2, 2, '2024-12-07 13:41:33');

-- ----------------------------
-- Table structure for matchs
-- ----------------------------
DROP TABLE IF EXISTS `matchs`;
CREATE TABLE `matchs`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `team1` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `team2` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `time_begin` datetime(0) NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 9 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of matchs
-- ----------------------------
INSERT INTO `matchs` VALUES (1, 'Arsenal\r\n', 'Everton', '2024-12-14 16:55:32');
INSERT INTO `matchs` VALUES (2, 'Liverpool\r\n', '\r\nFulham', '2024-12-14 16:55:36');
INSERT INTO `matchs` VALUES (3, 'Newcastle United\r\n', 'Leicester City', '2024-12-14 21:55:42');
INSERT INTO `matchs` VALUES (4, 'Wolverhampton Wanderers\r\n', 'Ipswich Town', '2024-12-14 20:55:50');
INSERT INTO `matchs` VALUES (5, 'Nottingham Forest\r\n', 'Aston Villa', '2024-12-15 16:54:48');
INSERT INTO `matchs` VALUES (6, 'Brighton & Hove Albion', 'Crystal Palace', '2024-12-15 22:56:00');
INSERT INTO `matchs` VALUES (7, 'Manchester City\r\n', 'Manchester United', '2024-12-15 16:56:07');
INSERT INTO `matchs` VALUES (8, 'Chelsea\r\n', 'Brentford', '2024-12-15 23:56:14');

-- ----------------------------
-- Table structure for ranking
-- ----------------------------
DROP TABLE IF EXISTS `ranking`;
CREATE TABLE `ranking`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `team` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `number_match` int(11) NOT NULL,
  `win` int(11) NOT NULL,
  `draw` int(11) NOT NULL,
  `lose` int(11) NOT NULL,
  `goal` int(11) NOT NULL,
  `goal_conceded` int(11) NOT NULL,
  `point` int(11) NOT NULL,
  `created_at` datetime(0) NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 16 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of ranking
-- ----------------------------
INSERT INTO `ranking` VALUES (1, 'Liverpool', 15, 11, 2, 2, 29, 11, 35, '0000-00-00 00:00:00');
INSERT INTO `ranking` VALUES (2, 'Chelsea', 15, 10, 3, 2, 34, 11, 34, '0000-00-00 00:00:00');
INSERT INTO `ranking` VALUES (3, 'Arsenal\r\n', 15, 9, 4, 1, 36, 12, 32, '0000-00-00 00:00:00');
INSERT INTO `ranking` VALUES (4, 'Manchester City\r\n', 15, 9, 4, 1, 35, 16, 29, '0000-00-00 00:00:00');
INSERT INTO `ranking` VALUES (5, 'Nottingham Forest', 15, 8, 4, 3, 25, 16, 28, '0000-00-00 00:00:00');
INSERT INTO `ranking` VALUES (6, 'Aston Villa', 15, 8, 5, 2, 23, 18, 27, '0000-00-00 00:00:00');
INSERT INTO `ranking` VALUES (7, 'Brighton & Hove Albion', 15, 7, 3, 5, 12, 14, 25, '0000-00-00 00:00:00');
INSERT INTO `ranking` VALUES (8, 'AFC Bournemouth', 15, 7, 4, 4, 33, 16, 24, '0000-00-00 00:00:00');
INSERT INTO `ranking` VALUES (9, 'Brentford', 15, 6, 3, 6, 45, 16, 22, '0000-00-00 00:00:00');
INSERT INTO `ranking` VALUES (10, 'Tottenham Hotspur', 15, 6, 3, 6, 22, 18, 21, '0000-00-00 00:00:00');
INSERT INTO `ranking` VALUES (11, 'Newcastle United', 15, 5, 7, 3, 25, 17, 20, '0000-00-00 00:00:00');
INSERT INTO `ranking` VALUES (12, 'Manchester United', 15, 5, 5, 5, 26, 23, 18, '0000-00-00 00:00:00');
INSERT INTO `ranking` VALUES (13, 'West Ham United', 15, 4, 2, 9, 27, 20, 17, '0000-00-00 00:00:00');
INSERT INTO `ranking` VALUES (14, 'Everton', 15, 4, 3, 8, 29, 19, 17, '0000-00-00 00:00:00');
INSERT INTO `ranking` VALUES (15, 'Leicester City', 15, 3, 5, 7, 20, 18, 15, '0000-00-00 00:00:00');

SET FOREIGN_KEY_CHECKS = 1;
